### ISSUE TITLE
TypeError 

### ISSUE THREAD

**Issue by vlpraveen** [blipk/StreamlitExtras#9]
Hi, I don't have the luxury of upgrading python from 3.9.2 any sooner in the production. Could you please say which version of the threading module is supported ? I keep getting this error

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
2024-01-13 19:31:59.623 Uncaught app exception
Traceback (most recent call last):
  File "/home/.local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/pic/my_streamlit.py", line 17, in <module>
    from streamlitextras.threader import streamlit_thread
  File "/home/.local/lib/python3.9/site-packages/streamlitextras/threader/__init__.py", line 70, in <module>
    script_run_context: ScriptRunContext | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by blipk** [comment]
@vlpraveen 

You will have to use a version before 0.2.40 most likely, or perhaps even earlier.

You can see the versions here: https://pypi.org/project/streamlit-base-extras/#history

Try one until you find one that works for your python version.

Newer versions will only support 3.10+
